-- DIMENSION TABLES
CREATE OR REPLACE TABLE DIM_PATIENT AS
SELECT DISTINCT
    NAME AS PATIENT_NAME,
    AGE,
    GENDER,
    "Blood Type" AS BLOOD_TYPE,
    "Medical Condition" AS MEDICAL_CONDITION
FROM HEALTHCARE_RAW;

CREATE OR REPLACE TABLE DIM_DOCTOR AS
SELECT DISTINCT
    DOCTOR AS DOCTOR_NAME
FROM HEALTHCARE_RAW;

CREATE OR REPLACE TABLE DIM_HOSPITAL AS
SELECT DISTINCT
    HOSPITAL AS HOSPITAL_NAME,
    "Insurance Provider" AS INSURANCE_PROVIDER
FROM HEALTHCARE_RAW;

CREATE OR REPLACE TABLE DIM_MEDICATION AS
SELECT DISTINCT
    MEDICATION
FROM HEALTHCARE_RAW;

-- FACT TABLE
CREATE OR REPLACE TABLE FACT_ADMISSION AS
SELECT
    NAME AS PATIENT_NAME,
    DOCTOR AS DOCTOR_NAME,
    HOSPITAL AS HOSPITAL_NAME,
    MEDICATION,
    "Date of Admission" AS ADMISSION_DATE,
    "Discharge Date" AS DISCHARGE_DATE,
    "Admission Type" AS ADMISSION_TYPE,
    "Room Number" AS ROOM_NUMBER,
    "Billing Amount" AS BILLING_AMOUNT
FROM HEALTHCARE_RAW;

-- PRACTICE QUERIES
-- 1. Latest admission per patient
WITH latest_admission AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY PATIENT_NAME 
            ORDER BY ADMISSION_DATE DESC
        ) AS rn
    FROM FACT_ADMISSION
)
SELECT * FROM latest_admission WHERE rn = 1;

-- 2. Billing above average
SELECT *
FROM FACT_ADMISSION
WHERE BILLING_AMOUNT > (SELECT AVG(BILLING_AMOUNT) FROM FACT_ADMISSION);

-- 3. Top 5 costliest admissions
WITH cost_rank AS (
    SELECT *,
        RANK() OVER (ORDER BY BILLING_AMOUNT DESC) AS rk
    FROM FACT_ADMISSION
)
SELECT * FROM cost_rank WHERE rk <= 5;

-- 4. Average billing by hospital
SELECT 
    HOSPITAL_NAME,
    AVG(BILLING_AMOUNT) AS AVG_BILL
FROM FACT_ADMISSION
GROUP BY HOSPITAL_NAME
ORDER BY AVG_BILL DESC;

-- 5. Patient — Doctor — Hospital Analytics View
SELECT 
    p.PATIENT_NAME,
    p.AGE,
    d.DOCTOR_NAME,
    h.HOSPITAL_NAME,
    f.ADMISSION_DATE,
    f.DISCHARGE_DATE,
    f.BILLING_AMOUNT
FROM FACT_ADMISSION f
JOIN DIM_PATIENT p ON f.PATIENT_NAME = p.PATIENT_NAME
JOIN DIM_DOCTOR d ON f.DOCTOR_NAME = d.DOCTOR_NAME
JOIN DIM_HOSPITAL h ON f.HOSPITAL_NAME = h.HOSPITAL_NAME;
